# MIT License - Copyright (c) 2020 Stefan Arentz <stefan@devbots.xyz>
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

name: 'Xcode Notarize'
description: 'Notarize your Mac application or plugin.'

branding:
  icon: 'command'
  color: 'blue'

inputs:
  product-path:
    description: "Path to the product to notarize."
    required: true
  apple-id:
    description: 'The Apple ID to use.'
    required: true
  team-id:
    description: 'The Team ID to use.'
    required: false
  app-password:
    description: 'The app-specific password to use.'
    required: true
  verbose:
    description: "Verbose mode will print Notarization API responses."
    required: false
    default: false

outputs:
  product-path:
    description: "Path to the product that was notarized"

runs:
  using: 'node20'
  main: 'dist/index.js'
